services:
  - type: web
    name: my-n8n
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://live-n8n-dhoy.onrender.com
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"
